# Generated by Django 4.2.20 on 2025-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(default='perfumes/default.jpg', upload_to='perfumes/'),
            preserve_default=False,
        ),
    ]
